import type { Metadata } from 'next';
import type { ReactNode } from 'react';
import './globals.css';
import { LocaleProvider } from '@/components/providers/locale-provider';
import { LanguageToggle } from '@/components/language-toggle';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <LocaleProvider>
          <div className="fixed right-4 top-4 z-50">
            <LanguageToggle />
          </div>
          {children}
        </LocaleProvider>
      </body>
    </html>
  );
}
